name: Deployment of current GitHub repo on a server through SSH
on:
  push:
    branches: [prod]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Rxinui/ssh-deploy-repo-action@v1
        with:
          # Required
          ssh-user: ${{ secrets.MISH_USERNAME }}
          ssh-password: ${{ secrets.MISH_PASSWORD }}
          ssh-domain: ${{ secrets.MISH_HOST }}
          # Optional
          git-clone-by: ssh
          target-branch: prod
          target-directory: /mishu/
